### ISSUE TITLE
Artwork Support?

### ISSUE THREAD

**Issue by AKASGaming** [RayPS/obs-spotify-mac#1]
Could you please kindly add Artwork support for this?
If i'm looking at the code correctly, you're using AppleScript to run the commands to Spotify. [With this](https://wiki.dhruvs.space/tools/mac/applescript/applescript-for-spotify), you should be able to collect the Artwork for the current song, and maybe let this run through a Browser Source.

Thanks in advance, and great job with this!

**Comment by RayPS** [comment]
Hi I just added this feature as you demand, can you give it a test?

**Comment by AKASGaming** [comment]
Works great! Thanks for adding this dude!
