### ISSUE TITLE
Failed to call script_properties

### ISSUE THREAD

**Issue by danielpassos** [RayPS/obs-spotify-mac#2]
I'm getting this error when I install the script

Mac OS: 13.1 (22C65)
Chip: Apple M1 Pro
OBS Version: 27.2.4 (64 Bits)

```
[spotify.lua] script_update
[spotify.lua] Failed to call script_properties for obs_lua_script_get_properties: spotify.lua:116: Error in obs_properties_add_text (arg 4), expected 'enum obs_text_type' got 'nil'
[spotify.lua] Failed to call script_properties for obs_lua_script_get_properties: spotify.lua:116: Error in obs_properties_add_text (arg 4), expected 'enum obs_text_type' got 'nil'
```
<img width="906" alt="CleanShot 2023-01-01 at 12 30 25@2x" src="https://user-images.githubusercontent.com/13337/210179697-86024c76-2c1f-460e-8e23-fdcc35cb6dd5.png">

**Comment by RayPS** [comment]
Your OBS version is a little bit older, can you try upgrading your OBS to v28?

**Comment by danielpassos** [comment]
Gotcha! I will give it a try on OBS 28 but unfortunately I can't upgrade yet because some others plugins that I use (and need) don't support it yet. Thanks for the quick reply anyway!

**Comment by danielpassos** [comment]
Just wondering if that is not a good idea to provides a minimum OBS version requirement on the README

**Comment by RayPS** [comment]
There is a workaround for you, you can just remove this line of code:
https://github.com/RayPS/obs-spotify-mac/blob/135fc058725c4c46fc9ed6891686941301084cf0/spotify.lua#L122
then it will work on OBS v27.

What this line do just add a text label above the option. (Which is a new text format introduced in V28)
Without this line you are only missing a text label on the GUI which is fine and won't affect any functionality.
![Screenshot 2022-11-24 at 14 41 39@2x](https://user-images.githubusercontent.com/1941540/210186256-da8b4679-8e7d-415e-a45b-20c48092b7f6.png)

**Comment by RayPS** [comment]
Let me know if that works and I will add this issue to the README as a reminder for OBS v27 users.

**Comment by danielpassos** [comment]
It works like a charm. Thanks!

**Comment by danielpassos** [comment]
PS: You should also add a way to people donate, like [Buy me a coffee](https://www.buymeacoffee.com/) or something like that.

**Comment by RayPS** [comment]
Thank you! I will also add [paypal.me/rayps](https://paypal.me/rayps) to the README.
