### ISSUE TITLE
separate lines?

### ISSUE THREAD

**Issue by 02days** [RayPS/obs-spotify-mac#3]
i'm sorry if this is a stupid question, i am clueless when it comes to code and i tried to google but nothing seemed to work, would it be possible to put the name and artist on separate lines somehow? everything i've tried hasn't worked so wasn't sure if it was possible or if my lack of coding knowledge is to blame haha

i am loving the tool though!

**Comment by RayPS** [comment]
This is a great suggestion! I'm not sure why I didn't think of line breaking before. I've already added the feature and would appreciate your feedback on the latest version. The usage description in the README has also been updated accordingly. Thank you very much!
